id: A8BDDFCDE
base_file: fEED9.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:39:08.908527
  last_modified_at: 2022-06-11 13:39:08.908534
